//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionHR.Web.UI.Forms.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ComboBoxValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComboBoxValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionHR.Web.UI.Forms.App_GlobalResources.ComboBoxValues", typeof(ComboBoxValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BEBAAqtypeProgressive {
            get {
                return ResourceManager.GetString("BEBAAqtypeProgressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BEBAAqtypeUnbound {
            get {
                return ResourceManager.GetString("BEBAAqtypeUnbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BEBADeliveryTypeCash {
            get {
                return ResourceManager.GetString("BEBADeliveryTypeCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BEBADeliveryTypeService {
            get {
                return ResourceManager.GetString("BEBADeliveryTypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BEBSAqtypeProgressive {
            get {
                return ResourceManager.GetString("BEBSAqtypeProgressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string BEBSAqtypeUnbound {
            get {
                return ResourceManager.GetString("BEBSAqtypeUnbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CMCAStatusClosed {
            get {
                return ResourceManager.GetString("CMCAStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CMCAStatusOpen {
            get {
                return ResourceManager.GetString("CMCAStatusOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CMCAStatusPending {
            get {
                return ResourceManager.GetString("CMCAStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string CMCAStatusPrefAll {
            get {
                return ResourceManager.GetString("CMCAStatusPrefAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string CMCAStatusPrefClosed {
            get {
                return ResourceManager.GetString("CMCAStatusPrefClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CMCAStatusPrefOpen {
            get {
                return ResourceManager.GetString("CMCAStatusPrefOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CMCAStatusPrefPending {
            get {
                return ResourceManager.GetString("CMCAStatusPrefPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CSDETypeAdministration {
            get {
                return ResourceManager.GetString("CSDETypeAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string CSDETypeSection {
            get {
                return ResourceManager.GetString("CSDETypeSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ECCOStatusClosed {
            get {
                return ResourceManager.GetString("ECCOStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ECCOStatusPefPending {
            get {
                return ResourceManager.GetString("ECCOStatusPefPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string ECCOStatusPending {
            get {
                return ResourceManager.GetString("ECCOStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ECCOStatusPrefAll {
            get {
                return ResourceManager.GetString("ECCOStatusPrefAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string ECCOStatusPrefClosed {
            get {
                return ResourceManager.GetString("ECCOStatusPrefClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EPDEDependencyTypeChild {
            get {
                return ResourceManager.GetString("EPDEDependencyTypeChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string EPDEDependencyTypeDomesticPartner {
            get {
                return ResourceManager.GetString("EPDEDependencyTypeDomesticPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string EPDEDependencyTypeFosterChild {
            get {
                return ResourceManager.GetString("EPDEDependencyTypeFosterChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EPDEDependencyTypeSpouse {
            get {
                return ResourceManager.GetString("EPDEDependencyTypeSpouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string EPDEDependencyTypeStepChild {
            get {
                return ResourceManager.GetString("EPDEDependencyTypeStepChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EPEMInactivePrefAll {
            get {
                return ResourceManager.GetString("EPEMInactivePrefAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string EPEMRehireNo {
            get {
                return ResourceManager.GetString("EPEMRehireNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EPEMRehireNotYetKnown {
            get {
                return ResourceManager.GetString("EPEMRehireNotYetKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EPEMRehireYes {
            get {
                return ResourceManager.GetString("EPEMRehireYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string EPEMReligionBudha {
            get {
                return ResourceManager.GetString("EPEMReligionBudha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string EPEMReligionChristian {
            get {
                return ResourceManager.GetString("EPEMReligionChristian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string EPEMReligionHindu {
            get {
                return ResourceManager.GetString("EPEMReligionHindu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EPEMReligionJew {
            get {
                return ResourceManager.GetString("EPEMReligionJew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EPEMReligionMuslim {
            get {
                return ResourceManager.GetString("EPEMReligionMuslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string EPEMReligionOther {
            get {
                return ResourceManager.GetString("EPEMReligionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string EPEMReligionSeikh {
            get {
                return ResourceManager.GetString("EPEMReligionSeikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string EPEMttIdCompany {
            get {
                return ResourceManager.GetString("EPEMttIdCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string EPEMttIdOther {
            get {
                return ResourceManager.GetString("EPEMttIdOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string EPEMttIdWorker {
            get {
                return ResourceManager.GetString("EPEMttIdWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string LMLRStatusApproved {
            get {
                return ResourceManager.GetString("LMLRStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string LMLRStatusPending {
            get {
                return ResourceManager.GetString("LMLRStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string LMLRStatusRefused {
            get {
                return ResourceManager.GetString("LMLRStatusRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string LMLRStatusUsed {
            get {
                return ResourceManager.GetString("LMLRStatusUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PYEMPaymentFrequencyBiWeekly {
            get {
                return ResourceManager.GetString("PYEMPaymentFrequencyBiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PYEMPaymentFrequencyDaily {
            get {
                return ResourceManager.GetString("PYEMPaymentFrequencyDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PYEMPaymentFrequencyFourWeekly {
            get {
                return ResourceManager.GetString("PYEMPaymentFrequencyFourWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PYEMPaymentFrequencyMonthly {
            get {
                return ResourceManager.GetString("PYEMPaymentFrequencyMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PYEMPaymentFrequencyWeekly {
            get {
                return ResourceManager.GetString("PYEMPaymentFrequencyWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PYEMPaymentMethodBank {
            get {
                return ResourceManager.GetString("PYEMPaymentMethodBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PYEMPaymentMethodCash {
            get {
                return ResourceManager.GetString("PYEMPaymentMethodCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PYEMpctOf1 {
            get {
                return ResourceManager.GetString("PYEMpctOf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PYEMpctOf2 {
            get {
                return ResourceManager.GetString("PYEMpctOf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string PYEMsalaryTypeBiWeekly {
            get {
                return ResourceManager.GetString("PYEMsalaryTypeBiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string PYEMsalaryTypeDaily {
            get {
                return ResourceManager.GetString("PYEMsalaryTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string PYEMsalaryTypeFourWeekly {
            get {
                return ResourceManager.GetString("PYEMsalaryTypeFourWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string PYEMsalaryTypeMonthly {
            get {
                return ResourceManager.GetString("PYEMsalaryTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string PYEMsalaryTypeWeekly {
            get {
                return ResourceManager.GetString("PYEMsalaryTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string RT110DimensionBranch {
            get {
                return ResourceManager.GetString("RT110DimensionBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string RT110DimensionDepartment {
            get {
                return ResourceManager.GetString("RT110DimensionDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string RT110DimensionDivision {
            get {
                return ResourceManager.GetString("RT110DimensionDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string RT110DimensionEHStatus {
            get {
                return ResourceManager.GetString("RT110DimensionEHStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string RT110DimensionPosition {
            get {
                return ResourceManager.GetString("RT110DimensionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SSCOStatusClosed {
            get {
                return ResourceManager.GetString("SSCOStatusClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SSCOStatusPending {
            get {
                return ResourceManager.GetString("SSCOStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SSEMReligionBudha {
            get {
                return ResourceManager.GetString("SSEMReligionBudha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string SSEMReligionChristian {
            get {
                return ResourceManager.GetString("SSEMReligionChristian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string SSEMReligionHindu {
            get {
                return ResourceManager.GetString("SSEMReligionHindu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SSEMReligionJew {
            get {
                return ResourceManager.GetString("SSEMReligionJew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SSEMReligionMuslim {
            get {
                return ResourceManager.GetString("SSEMReligionMuslim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string SSEMReligionOther {
            get {
                return ResourceManager.GetString("SSEMReligionOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string SSEMReligionSeikh {
            get {
                return ResourceManager.GetString("SSEMReligionSeikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SYLMLRStatusApproved {
            get {
                return ResourceManager.GetString("SYLMLRStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SYLMLRStatusNew {
            get {
                return ResourceManager.GetString("SYLMLRStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string SYLMLRStatusRefused {
            get {
                return ResourceManager.GetString("SYLMLRStatusRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string SYLTLRApprovalLoanStatusApproved {
            get {
                return ResourceManager.GetString("SYLTLRApprovalLoanStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SYLTLRApprovalLoanStatusInProcess {
            get {
                return ResourceManager.GetString("SYLTLRApprovalLoanStatusInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SYLTLRApprovalLoanStatusNew {
            get {
                return ResourceManager.GetString("SYLTLRApprovalLoanStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string SYLTLRApprovalLoanStatusRejected {
            get {
                return ResourceManager.GetString("SYLTLRApprovalLoanStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SYTATATimeStatusApproved {
            get {
                return ResourceManager.GetString("SYTATATimeStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1.
        /// </summary>
        internal static string SYTATATimeStatusRefused {
            get {
                return ResourceManager.GetString("SYTATATimeStatusRefused", resourceCulture);
            }
        }
    }
}
