//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AionHR.Web.UI.Forms.Reports.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RT201_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RT201_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AionHR.Web.UI.Forms.Reports.App_LocalResources.RT201.aspx", typeof(RT201_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Only.
        /// </summary>
        internal static string ActiveOnly {
            get {
                return ResourceManager.GetString("ActiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hirings.
        /// </summary>
        internal static string Additions {
            get {
                return ResourceManager.GetString("Additions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Info.
        /// </summary>
        internal static string BasicInfoTabEditWindowTitle {
            get {
                return ResourceManager.GetString("BasicInfoTabEditWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string BOGridTitle {
            get {
                return ResourceManager.GetString("BOGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deductions.
        /// </summary>
        internal static string Deductions {
            get {
                return ResourceManager.GetString("Deductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeductionsEntitlements.
        /// </summary>
        internal static string DeductionsEntitlements {
            get {
                return ResourceManager.GetString("DeductionsEntitlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus.
        /// </summary>
        internal static string EditBOWindowTitle {
            get {
                return ResourceManager.GetString("EditBOWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Salary.
        /// </summary>
        internal static string EditSAWindowTitle {
            get {
                return ResourceManager.GetString("EditSAWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # of Employees.
        /// </summary>
        internal static string EmployeeCount {
            get {
                return ResourceManager.GetString("EmployeeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlements.
        /// </summary>
        internal static string Entitlements {
            get {
                return ResourceManager.GetString("Entitlements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string FieldAccountNumber {
            get {
                return ResourceManager.GetString("FieldAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string FieldAmount {
            get {
                return ResourceManager.GetString("FieldAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string FieldBankName {
            get {
                return ResourceManager.GetString("FieldBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Amount.
        /// </summary>
        internal static string FieldBasicAmount {
            get {
                return ResourceManager.GetString("FieldBasicAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        internal static string FieldBranch {
            get {
                return ResourceManager.GetString("FieldBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Type.
        /// </summary>
        internal static string FieldBTName {
            get {
                return ResourceManager.GetString("FieldBTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string FieldComment {
            get {
                return ResourceManager.GetString("FieldComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string FieldComments {
            get {
                return ResourceManager.GetString("FieldComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date.
        /// </summary>
        internal static string FieldDate {
            get {
                return ResourceManager.GetString("FieldDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FieldDate1 {
            get {
                return ResourceManager.GetString("FieldDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction.
        /// </summary>
        internal static string FieldDeduction {
            get {
                return ResourceManager.GetString("FieldDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string FieldDepartment {
            get {
                return ResourceManager.GetString("FieldDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string FieldDivision {
            get {
                return ResourceManager.GetString("FieldDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string FieldEffectiveDate {
            get {
                return ResourceManager.GetString("FieldEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        internal static string FieldEmployee {
            get {
                return ResourceManager.GetString("FieldEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement.
        /// </summary>
        internal static string FieldEntitlement {
            get {
                return ResourceManager.GetString("FieldEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Amount.
        /// </summary>
        internal static string FieldFinalAmount {
            get {
                return ResourceManager.GetString("FieldFinalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        internal static string FieldFixedAmount {
            get {
                return ResourceManager.GetString("FieldFixedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldFullName {
            get {
                return ResourceManager.GetString("FieldFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include In total.
        /// </summary>
        internal static string FieldIncludeInTotal {
            get {
                return ResourceManager.GetString("FieldIncludeInTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Percentage.
        /// </summary>
        internal static string FieldIsPercentage {
            get {
                return ResourceManager.GetString("FieldIsPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsTaxable.
        /// </summary>
        internal static string FieldIsTaxable {
            get {
                return ResourceManager.GetString("FieldIsTaxable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string FieldMonth {
            get {
                return ResourceManager.GetString("FieldMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Frequency.
        /// </summary>
        internal static string FieldPaymentFrequency {
            get {
                return ResourceManager.GetString("FieldPaymentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        internal static string FieldPaymentMethod {
            get {
                return ResourceManager.GetString("FieldPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percentage.
        /// </summary>
        internal static string FieldPCT {
            get {
                return ResourceManager.GetString("FieldPCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string FieldPosition {
            get {
                return ResourceManager.GetString("FieldPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record ID.
        /// </summary>
        internal static string FieldRecordId {
            get {
                return ResourceManager.GetString("FieldRecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string FieldReference {
            get {
                return ResourceManager.GetString("FieldReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string FieldSACurrencyName {
            get {
                return ResourceManager.GetString("FieldSACurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalaryType.
        /// </summary>
        internal static string FieldSalaryType {
            get {
                return ResourceManager.GetString("FieldSalaryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Reason.
        /// </summary>
        internal static string FieldScrName {
            get {
                return ResourceManager.GetString("FieldScrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive Only.
        /// </summary>
        internal static string InactiveOnly {
            get {
                return ResourceManager.GetString("InactiveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late.
        /// </summary>
        internal static string LatenessGridTitle {
            get {
                return ResourceManager.GetString("LatenessGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string PaymentMethodBank {
            get {
                return ResourceManager.GetString("PaymentMethodBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string PaymentMethodCash {
            get {
                return ResourceManager.GetString("PaymentMethodCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string PaymentTypeDaily {
            get {
                return ResourceManager.GetString("PaymentTypeDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string PaymentTypeMonthly {
            get {
                return ResourceManager.GetString("PaymentTypeMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string PaymentTypeWeekly {
            get {
                return ResourceManager.GetString("PaymentTypeWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary .
        /// </summary>
        internal static string SAGridTitle {
            get {
                return ResourceManager.GetString("SAGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string SalaryBank {
            get {
                return ResourceManager.GetString("SalaryBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash.
        /// </summary>
        internal static string SalaryCash {
            get {
                return ResourceManager.GetString("SalaryCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        internal static string SalaryDaily {
            get {
                return ResourceManager.GetString("SalaryDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string SalaryMonthly {
            get {
                return ResourceManager.GetString("SalaryMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string SalaryWeekly {
            get {
                return ResourceManager.GetString("SalaryWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminations.
        /// </summary>
        internal static string Terminations {
            get {
                return ResourceManager.GetString("Terminations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string WindowTitle1 {
            get {
                return ResourceManager.GetString("WindowTitle1", resourceCulture);
            }
        }
    }
}
